# Generated by Django 3.2 on 2021-05-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='opg_stock',
            field=models.FloatField(default=0),
        ),
    ]
