# Generated by Django 3.2 on 2021-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210501_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='ref',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='ref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
